version: '3'
services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    image: gameboi_backend
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - db
  ui:
    build: ./ui
    image: gameboi_ui
    ports:
      - "3000:3000"